// {{ cookiecutter.project_slug }}/frontend/react/src/App.tsx
export default function App() {
  return (
    <div className="text-center">
      <h2 className="text-xl font-semibold text-sky-700">React + Vite + Tailwind</h2>
      <p className="mt-2 text-sm text-slate-600">
        Mounted into <code>#app</code> from Django template.
      </p>
    </div>
  );
}

// {{ cookiecutter.project_slug }}/frontend/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";

const title = ref("Vue + Vite + Tailwind");
</script>

<template>
  <div class="text-center">
    <h2 class="text-xl font-semibold text-emerald-700">{{ title }}</h2>
    <p class="mt-2 text-sm text-slate-600">Mounted into <code>#app</code> from Django template.</p>
  </div>
</template>
